### ISSUE TITLE
blkid options is non portable

### ISSUE THREAD

**Issue by illiliti** [kisslinux/init#13]
toybox and busybox doesn't have these options
https://github.com/kisslinux/init/blob/e2840bdc5d8f80a0b23b692e2a72c2383eedc4c4/lib/init/rc.lib#L42

**Comment by dylanaraps** [comment]
Any ideas on how to fix this? I don't personally use encryption and can't test any fixes anyway really.

**Comment by illiliti** [comment]
I'll do a pull request shortly
