### ISSUE TITLE
(?) Changing init system from busybox to vanilla runit

### ISSUE THREAD

**Issue by quisys** [kisslinux/init#20]
Hi, I hope this is the right place to ask this.

I am having a hard time with busybox's init system, but can't find any documentation detailing how to change the init system on kiss, how do I do it?

Again, sorry if this is not the correct place to ask

**Comment by dylanaraps** [comment]
It should be as simple as installing the `runit` package from Community and running `kiss a runit /usr/bin/init` (`kiss a` with no arguments will tell you if there are any other binaries you must swap to). @cemkeylan, care to confirm? Documentation is lacking here, will write a page for the Wiki about this. :+1:

**Comment by cemkeylan** [comment]
That's true, you will also need to run

```sh
kiss a runit /usr/bin/poweroff
kiss a runit /usr/bin/reboot
```

**Comment by quisys** [comment]
woah! `kiss a` is amazing, can't believe that I didn't know about that before. 
Thanks for the quick response, have a good one.

**Comment by dylanaraps** [comment]
Page is live (though only covers runit for the time being. Will be expanded over time). https://k1ss.org/wiki/init/changing-init

**Comment by cemkeylan** [comment]
I have also sent you a mail patch for the wiki including a more detailed page for switching init systems and also a wiki page for `sysmgr`

**Comment by cemkeylan** [comment]
Also, since runit provides both init and service supervisor, doing

`kiss a | grep ^runit | kiss a -` will result in both of them to be replaced, not just init.
