### ISSUE TITLE
Boot goes to emergency shell

### ISSUE THREAD

**Issue by quisys** [kisslinux/init#22]
At the "checking filesystems" portion of init, I get

```
/dev/sdb3: clean, 12/29048832 files, [more numbers] blocks
fsck.fat 4.2 (2017-01-24)
open: No such file or directory
/dev/sda2: clean, [numbers] files, [even more numbers] blocks
=> Init system encountered an error, starting emergency shell.
=> When ready, type 'exit' to continue the boot
```

I am using default init and have dosfstools installed. It's trying to check /dev/sdb3 (fat32) but failing for some reason.

**Comment by quisys** [comment]
Fixed by using /dev/sdXX in fstab instead of UUIDs, still a weird issue through.

**Comment by dylanaraps** [comment]
This is working as intended, `fsck` failed which drops you into an emergency shell. 

Now, according to busybox's `sources when `UUID` is used it'll try to execute `fsck.auto`. This executable doesn't exist which causes the open error I believe.

Will look into this.

**Comment by dylanaraps** [comment]
Swapping from busybox's utilities to util-linux's will allow you to use UUIDs. busybox is rather barebones.
